
[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/jsonutils"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/log"

[[constraint]]
  branch = "release/2.2.0"
  name = "yunion.io/x/onecloud"

[[constraint]]
  branch = "master"
  name = "yunion.io/x/pkg"

[prune]
  go-tests = true
  unused-packages = true
